[doc] gtfs2ntfs: precision on line comments
CanalTP/transit_model pull request #736
Opened 2021-01-29 11:26 UTC by papailio

cf. ND-1075

2021-02-02 10:10 UTC, pbougue approved these changes
minor comments only

2021-02-02 10:10 UTC, pbougue commented on documentation/gtfs_to_ntfs_specs.md
> +| comments.txt | comment_value  | Optional   | routes.txt | route_desc      | The comment is generated only when the parameter `read-as-line` deactivated. See (3) for additional properties
```suggestion
| comments.txt | comment_value  | Optional   | routes.txt | route_desc      | The comment is generated only when the parameter `read-as-line` is deactivated. See (3) for additional properties                                                                                                                           |
```

2021-02-02 10:10 UTC, pbougue commented on documentation/gtfs_to_ntfs_specs.md
> +| comments.txt | comment_value | Optional | routes.txt | route_desc | The comment is generated only when the parameter `read-as-line` activated. See (2) for additional properties. |
```suggestion
| comments.txt | comment_value | Optional | routes.txt | route_desc | The comment is generated only when the parameter `read-as-line` is activated. See (2) for additional properties. |
```

2021-02-02 10:10 UTC, woshilapin requested changes

2021-02-02 10:10 UTC, woshilapin commented on documentation/gtfs_to_ntfs_specs.md
> +| comments.txt | comment_value  | Optional   | routes.txt | route_desc      | The comment is generated only when the parameter `read-as-line` deactivated. See (3) for additional properties
```suggestion
| comments.txt | comment_value  | Optional   | routes.txt | route_desc      | The comment is generated only when the parameter `read-as-line` is deactivated. See (3) for additional properties                                                                                                                           |
```

2021-02-02 10:10 UTC, woshilapin commented on documentation/gtfs_to_ntfs_specs.md
> +| comments.txt | comment_value | Optional | routes.txt | route_desc | The comment is generated only when the parameter `read-as-line` activated. See (2) for additional properties. |
```suggestion
| comments.txt | comment_value | Optional | routes.txt | route_desc | The comment is generated only when the parameter `read-as-line` is activated. See (2) for additional properties. |
```

2021-02-05 09:01 UTC, woshilapin approved these changes

2021-02-05 09:01 UTC, woshilapin commented
Good for me but the commit has been integrated and will be merged through #741. I'm closing the current PR.

2021-02-05 09:01 UTC, closed without merging